### ISSUE TITLE
pytorch_model.bin Pre-training model read error

### ISSUE THREAD

**Issue by maxin0002** [LiheYoung/Depth-Anything#106]
Thank you very much for such a wonderful job! When I was using the local load of the model, I followed your tutorial and downloaded the `config.json` and the `pytorch_model.bin` from the [vitl](https://huggingface.co/LiheYoung/depth_anything_vitl14) page, but when I run python run.py, `FileNotFoundError: No such file or directory: "checkpoints/depth_anything_vitl14/model.safetensors"` error, I don't know if you gave the wrong link address? But I use the `depth_anything_vitl14_hf` link for the pre-trained model, and the `config.json` gives the undefined keyword error again, and I need to empty the file to run it.

**Comment by LiheYoung** [comment]
Hi, thank you very much for your feedback. I have updated the [instructions](https://github.com/LiheYoung/Depth-Anything#no-network-connection-cannot-load-these-models) to load our pre-trained models without network connections. Please also take care of the updated downloading links of our checkpoints. Please let me know if you encounter any other problems.

**Comment by gengh23** [comment]
Hi,do you solve it?

**Comment by maxin0002** [comment]
Yes, I solved the above problems, after the author's latest update. Thanks to the author ~
