### ISSUE TITLE
Best inference config?

### ISSUE THREAD

**Issue by huchenlei** [LiheYoung/Depth-Anything#11]
I just added depth_anything as a preprocessor to sd-webui-controlnet. However, the preprocessor does not do better than leres depth. Is there any finetuning of params necessary for best performance / any bug in my implementation?

https://github.com/Mikubill/sd-webui-controlnet/discussions/2549
https://github.com/Mikubill/sd-webui-controlnet/pull/2544

**Comment by LiheYoung** [comment]
Hi chenlei, thank you for your implementation! I checked the implementation and it should be right. And thank you for your comparison case! I checked it and found that actually our Depth Anything produces more accurate relative depth estimation, especially the regions I highlighted below, *e.g.*, the relative depth between the flowers near the wall and the sofa. Some other methods may predict relatively farther objects as closer ones.

<img width="1605" alt="截屏2024-01-23 13 06 45" src="https://github.com/LiheYoung/Depth-Anything/assets/47178369/bf004b73-27ed-4cfe-8e44-308d8182b179">

**Comment by huchenlei** [comment]
Thanks for the proofread! We will continue to follow the updates in depth anything improvements. I was also reminded that depth anything is superior handling motion blur and has better temporal stability which is not demonstrated in the example. I have included these in the release note.
