### ISSUE TITLE
How to generate cloudpoint？

### ISSUE THREAD

**Issue by Alex86706** [LiheYoung/Depth-Anything#119]
I try to use the 'geometry.py' to generate the cloudpoint,but it get a bad result.

**Comment by Nazaninpdk** [comment]
you can use open3D 
[https://github.com/isl-org/Open3D](url)


`
import numpy as np
import open3d

rgb_path = "C:/Users/User/Desktop//01_Camera1.jpg"
depth_path = "C:/Users/User/Desktop//01_Camera1.png"

depth_image = open3d.io.read_image(depth_path)
depth_array = np.array(depth_image)
#array = np.zeros((4016,6016))
#for i in range(4016):
    #for j in range(6016):
        #array[i,j] = depth_array[i,j,0]
##depth_array = ((array - np.min(array) * (1/(np.max(array) - np.min(array)) ) )).astype('uint8')
#print(np.shape(depth_array),np.shape(array))

#depth_image = open3d.geometry.Image(depth_array)
image_width = int(depth_image.get_max_bound()[0])
image_height = int(depth_image.get_max_bound()[1])

intrinsics = open3d.camera.PinholeCameraIntrinsic(width=image_width, height=image_height, cx=image_width / 2, cy=image_height / 2, fx=image_width / 2, fy=image_height / 2) # Put correct camera intrinsics parameters here

pc = open3d.geometry.PointCloud() # initialize Point Cloud

rgb_image_path = "C:/Users/User/Desktop/01_Camera1.jpg" # put image path here

rgb = open3d.io.read_image(rgb_image_path) # load RGB image

rgbd = open3d.geometry.RGBDImage.create_from_color_and_depth(rgb, depth_image, depth_scale=1, depth_trunc=10000, convert_rgb_to_intensity=False) # create RGBD image

pc = pc.create_from_rgbd_image(rgbd, intrinsics) # create point cloud from RGBD image

fcloud = "C:/Users/User/Desktop/01_nyu_point_test.ply"
open3d.io.write_point_cloud(fcloud, pc, write_ascii=False) # save point cloud

`

**Comment by Alex86706** [comment]
> 你可以使用 open3D [https://github.com/isl-org/Open3D](url)
> 
> ` 导入 numpy 作为 np 导入 o​​pen3d
> 
> rgb_path =“C：/用户/用户/桌面//01_Camera1.jpg” 深度路径=“C：/用户/用户/桌面//01_Camera1.png”
> 
> 深度图像 = open3d.io.read_image(深度路径) 深度数组 = np.array(深度图像) #array = np.zeros((4016,6016)) #for i in range(4016): #for j in range(6016): # array[i,j] = 深度数组[i,j,0] ##深度数组 = ((数组 - np.min(array) * (1/(np.max(array) - np.min(array)) ) ) ).astype('uint8') #print(np.shape(深度数组),np.shape(数组))
> 
> #深度图像 = open3d.geometry.Image(深度数组) 图像宽度 = int(深度图像.get_max_bound()[0]) 图像高度 = int(深度图像.get_max_bound()[1])
> 
> trinsic = open3d.camera.PinholeCameraIntrinsic(width=image_width, height=image_height, cx=image_width / 2, cy=image_height / 2, fx=image_width / 2, fy=image_height / 2) # 在此放置正确的相机内在参数
> 
> pc = open3d.geometry.PointCloud() # 初始化点云
> 
> rgb_image_path = "C:/Users/User/Desktop/01_Camera1.jpg" # 将图像路径放在这里
> 
> rgb = open3d.io.read_image(rgb_image_path) # 加载 RGB 图像
> 
> rgbd = open3d.geometry.RGBDImage.create_from_color_and_depth(rgb, depth_image, height_scale=1, height_trunc=10000, conversion_rgb_to_intensity=False) # 创建 RGBD 图像
> 
> pc = pc.create_from_rgbd_image(rgbd, insides) # 从 RGBD 图像创建点云
> 
> fcloud = "C:/Users/User/Desktop/01_nyu_point_test.ply" open3d.io.write_point_cloud(fcloud, pc, write_ascii=False) # 保存点云
> 
> `

**Comment by Alex86706** [comment]
sorry，I had try your code，but it get bad result
![截图 2024-03-15 18-10-27](https://github.com/LiheYoung/Depth-Anything/assets/48644959/c9efaa71-5a6f-4b3e-9f47-b3d435acaaf0)

**Comment by Alex86706** [comment]
> 你可以使用 open3D [https://github.com/isl-org/Open3D](url)
> 
> ` 导入 numpy 作为 np 导入 o​​pen3d
> 
> rgb_path =“C：/用户/用户/桌面//01_Camera1.jpg” 深度路径=“C：/用户/用户/桌面//01_Camera1.png”
> 
> 深度图像 = open3d.io.read_image(深度路径) 深度数组 = np.array(深度图像) #array = np.zeros((4016,6016)) #for i in range(4016): #for j in range(6016): # array[i,j] = 深度数组[i,j,0] ##深度数组 = ((数组 - np.min(array) * (1/(np.max(array) - np.min(array)) ) ) ).astype('uint8') #print(np.shape(深度数组),np.shape(数组))
> 
> #深度图像 = open3d.geometry.Image(深度数组) 图像宽度 = int(深度图像.get_max_bound()[0]) 图像高度 = int(深度图像.get_max_bound()[1])
> 
> trinsic = open3d.camera.PinholeCameraIntrinsic(width=image_width, height=image_height, cx=image_width / 2, cy=image_height / 2, fx=image_width / 2, fy=image_height / 2) # 在此放置正确的相机内在参数
> 
> pc = open3d.geometry.PointCloud() # 初始化点云
> 
> rgb_image_path = "C:/Users/User/Desktop/01_Camera1.jpg" # 将图像路径放在这里
> 
> rgb = open3d.io.read_image(rgb_image_path) # 加载 RGB 图像
> 
> rgbd = open3d.geometry.RGBDImage.create_from_color_and_depth(rgb, depth_image, height_scale=1, height_trunc=10000, conversion_rgb_to_intensity=False) # 创建 RGBD 图像
> 
> pc = pc.create_from_rgbd_image(rgbd, insides) # 从 RGBD 图像创建点云
> 
> fcloud = "C:/Users/User/Desktop/01_nyu_point_test.ply" open3d.io.write_point_cloud(fcloud, pc, write_ascii=False) # 保存点云
> 
> `

Thanks for your reply,I had try your code,but it got bad result.
![截图 2024-03-15 18-10-27](https://github.com/LiheYoung/Depth-Anything/assets/48644959/4090f135-d71a-448c-adce-e9fe71e444f8)

**Comment by Nazaninpdk** [comment]
> > 你可以使用 open3D [https://github.com/isl-org/Open3D](url)
> > ` 导入 numpy 作为 np 导入 o​​pen3d
> > rgb_path =“C：/用户/用户/桌面//01_Camera1.jpg” 深度路径=“C：/用户/用户/桌面//01_Camera1.png”
> > 深度图像 = open3d.io.read_image(深度路径) 深度数组 = np.array(深度图像) #array = np.zeros((4016,6016)) #for i in range(4016): #for j in range(6016): # array[i,j] = 深度数组[i,j,0] ##深度数组 = ((数组 - np.min(array) * (1/(np.max(array) - np.min(array)) ) ) ).astype('uint8') #print(np.shape(深度数组),np.shape(数组))
> > #深度图像 = open3d.geometry.Image(深度数组) 图像宽度 = int(深度图像.get_max_bound()[0]) 图像高度 = int(深度图像.get_max_bound()[1])
> > trinsic = open3d.camera.PinholeCameraIntrinsic(width=image_width, height=image_height, cx=image_width / 2, cy=image_height / 2, fx=image_width / 2, fy=image_height / 2) # 在此放置正确的相机内在参数
> > pc = open3d.geometry.PointCloud() # 初始化点云
> > rgb_image_path = "C:/Users/User/Desktop/01_Camera1.jpg" # 将图像路径放在这里
> > rgb = open3d.io.read_image(rgb_image_path) # 加载 RGB 图像
> > rgbd = open3d.geometry.RGBDImage.create_from_color_and_depth(rgb, depth_image, height_scale=1, height_trunc=10000, conversion_rgb_to_intensity=False) # 创建 RGBD 图像
> > pc = pc.create_from_rgbd_image(rgbd, insides) # 从 RGBD 图像创建点云
> > fcloud = "C:/Users/User/Desktop/01_nyu_point_test.ply" open3d.io.write_point_cloud(fcloud, pc, write_ascii=False) # 保存点云
> > `
> 
> Thanks for your reply,I had try your code,but it got bad result. ![截图 2024-03-15 18-10-27](https://private-user-images.githubusercontent.com/48644959/313153712-4090f135-d71a-448c-adce-e9fe71e444f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDE2MTgsIm5iZiI6MTcxMDU0MTMxOCwicGF0aCI6Ii80ODY0NDk1OS8zMTMxNTM3MTItNDA5MGYxMzUtZDcxYS00NDhjLWFkY2UtZTlmZTcxZTQ0NGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDIyMjE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MTE1ODZkNzQ2NmNhNjA4MmVhMGRjOTkzNjNiMmQzZTU4ZWJjNGFjNzc2M2FhNjgxMjUwMzdjMWI5ZTdlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JZ0FkB67lJ_Ccm5gxgyFvO62-8GPrJ8nHUyLAfkUmC4)


use you own camera parameters, cx, cy, fx, fy. And try to use the metric estimated depth for generating point clouds
