### ISSUE TITLE
Other models hosted on Huggingface transformers.

### ISSUE THREAD

**Issue by FreddieTAFreeth** [LiheYoung/Depth-Anything#124]
Hi Depth Anything Team,

I am writing a review paper of various CV models for use in a specific use case I will not go into at this time. I am assessing *Depth Anything* as part of my study. I have noticed that only the "small" model (LiheYoung/depth-anything-small-hf) is currently hosted on *Huggingspace* transformers, but not the larger models, which is unfortunate. Is it possible for you to host these there, or perhaps there is something I am missing?

Kind regards,
FTAF

**Comment by LiheYoung** [comment]
Hi, the [Depth-Anything-Base](https://huggingface.co/LiheYoung/depth-anything-base-hf) and [Depth-Anything-Large](https://huggingface.co/LiheYoung/depth-anything-large-hf) are also hosted on transformers.
