### ISSUE TITLE
Loading the weights 'locally' 

### ISSUE THREAD

**Issue by 0de554K** [LiheYoung/Depth-Anything#126]
Hi, 
It is not a good idea to use relative path in this case: 
https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/depth_anything/dpt.py#L147

In case point on working directory is different than repository root the runtime will try to find the file from wrong place and get "FileNotFoundError: [Errno 2] No such file or directory"

It is better to get repository root for sample:
`import os 
[...]
root = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
`
And use this variable in the path. 
Please take a look proposed patch in attachment.
[dpt.py.diff.txt](https://github.com/LiheYoung/Depth-Anything/files/14600969/dpt.py.diff.txt)

**Comment by LiheYoung** [comment]
Thank you for your advice. I will update our code.
