### ISSUE TITLE
C++ TensorRT Implementation

### ISSUE THREAD

**Issue by spacewalk01** [LiheYoung/Depth-Anything#13]
Thank you for providing your awesome work. I've implemented it using tensorrt api in c++: https://github.com/spacewalk01/depth-anything-tensorrt

**Comment by LiheYoung** [comment]
Hi @spacewalk01, thank you for your kind help! I will link to your repository in the updated README.  

BTW, is it convenient for you to report the inference time of all our three models with TensorRT, *i.e.,* ``Depth-Anything-S``, ``Depth-Anything-B``, and ``Depth-Anything-L``? I plan to add this information to our README. Thank you a lot!

**Comment by spacewalk01** [comment]
Okay. I will try to add inference time for all three models. Thank you

**Comment by spacewalk01** [comment]
Hi, Added the inference time for all three models. Really nice work.

**Comment by LiheYoung** [comment]
Thank you so much!! I will update this information in my repo and link it to your repo!

**Comment by LiheYoung** [comment]
Added! Thank you again!

**Comment by shilpaullas97** [comment]
Hi @spacewalk01 ,

Is the same TRT implementation applicable to the fine-tuned metric depth estimation models? (https://huggingface.co/spaces/LiheYoung/Depth-Anything/tree/main/checkpoints_metric_depth)
