### ISSUE TITLE
A config file lacking in the local model loading process

### ISSUE THREAD

**Issue by ZiQ-Li** [LiheYoung/Depth-Anything#138]
Dear Authors, here a problem confused me "TypeError: DepthAnything.__init__() missing 1 required positional argument: 'config'" when I load the local model by executing depth_anything = DepthAnything.from_pretrained('checkpoints/depth_anything_vitb14', local_files_only=True).to(DEVICE).eval(). But i cant find such a config file in hugface. Can you help me, PLZ

**Comment by LiheYoung** [comment]
Please refer to this: https://github.com/LiheYoung/Depth-Anything#no-network-connection-cannot-load-these-models by loading our models locally.
