### ISSUE TITLE
video input

### ISSUE THREAD

**Issue by zhw-zhang** [LiheYoung/Depth-Anything#14]
hi, thank you for your excellent work. How can I quickly use video as input?

**Comment by zwkkk** [comment]
https://github.com/zwkkk/Depth-Anything-Video

**Comment by zhw-zhang** [comment]
thanks

**Comment by loevlie** [comment]
Also, https://huggingface.co/spaces/JohanDL/Depth-Anything-Video

**Comment by LiheYoung** [comment]
Thank you @zwkkk and @loevlie! I have also uploaded my implementation for [video depth visualization](https://github.com/LiheYoung/Depth-Anything/blob/main/run_video.py).
