### ISSUE TITLE
About the Encoder feature

### ISSUE THREAD

**Issue by c-pupil** [LiheYoung/Depth-Anything#143]
i want get the feature from the pre-trained encoder，but the type of features is the tuple，and the lens of the features is 4，and each feature in the features  is also a  tuple, which lens is 2.How to obtain features from a pre-trained encoder with shape like BCHW?

**Comment by heyoeyo** [comment]
The length 2 tuple is likely the pairing of patch features with a class token. You can see how the [model uses the image encoder](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/depth_anything/dpt.py#L158) with a `return_class_token=True`, which results in the output patch features being [bundled with class tokens](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/torchhub/facebookresearch_dinov2_main/vision_transformer.py#L320) as a tuple. So the first item in those 2-tuples are the image patch features, the second item should be the class token.

The length 4 tuple should correspond to the 4 outputs the model sends to the DPT 'decoder' model (described in "[Vision Transformers for Dense Prediction](https://arxiv.org/abs/2103.13413)", see figure 1 especially). These comes from the last 4 layers of the model, so if you wanted just a single set of features, you could take a single item from that 4-tuple (either the first or last entry probably makes sense).

**Comment by c-pupil** [comment]
> The length 2 tuple is likely the pairing of patch features with a class token. You can see how the [model uses the image encoder](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/depth_anything/dpt.py#L158) with a `return_class_token=True`, which results in the output patch features being [bundled with class tokens](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/torchhub/facebookresearch_dinov2_main/vision_transformer.py#L320) as a tuple. So the first item in those 2-tuples are the image patch features, the second item should be the class token.
> 
> The length 4 tuple should correspond to the 4 outputs the model sends to the DPT 'decoder' model (described in "[Vision Transformers for Dense Prediction](https://arxiv.org/abs/2103.13413)", see figure 1 especially). These comes from the last 4 layers of the model, so if you wanted just a single set of features, you could take a single item from that 4-tuple (either the first or last entry probably makes sense).



> The length 2 tuple is likely the pairing of patch features with a class token. You can see how the [model uses the image encoder](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/depth_anything/dpt.py#L158) with a `return_class_token=True`, which results in the output patch features being [bundled with class tokens](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/torchhub/facebookresearch_dinov2_main/vision_transformer.py#L320) as a tuple. So the first item in those 2-tuples are the image patch features, the second item should be the class token.
> 
> The length 4 tuple should correspond to the 4 outputs the model sends to the DPT 'decoder' model (described in "[Vision Transformers for Dense Prediction](https://arxiv.org/abs/2103.13413)", see figure 1 especially). These comes from the last 4 layers of the model, so if you wanted just a single set of features, you could take a single item from that 4-tuple (either the first or last entry probably makes sense).

Thank you for your detailed explanation，which have addressed my question very well ！！！Thank you so much for your help!

**Comment by c-pupil** [comment]
> The length 2 tuple is likely the pairing of patch features with a class token. You can see how the [model uses the image encoder](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/depth_anything/dpt.py#L158) with a `return_class_token=True`, which results in the output patch features being [bundled with class tokens](https://github.com/LiheYoung/Depth-Anything/blob/6e780749e7772e911754a4eb00965727987f92f7/torchhub/facebookresearch_dinov2_main/vision_transformer.py#L320) as a tuple. So the first item in those 2-tuples are the image patch features, the second item should be the class token.
> 
> The length 4 tuple should correspond to the 4 outputs the model sends to the DPT 'decoder' model (described in "[Vision Transformers for Dense Prediction](https://arxiv.org/abs/2103.13413)", see figure 1 especially). These comes from the last 4 layers of the model, so if you wanted just a single set of features, you could take a single item from that 4-tuple (either the first or last entry probably makes sense).

Thank you for your detailed explanation，which have addressed my question very well ！！！Thank you so much for your help!
