### ISSUE TITLE
Why do the predicted disparity of vits, vitb, and vitl have different ranges?

### ISSUE THREAD

**Issue by WeijianZhang123** [LiheYoung/Depth-Anything#157]
I run run.py on assets/examples images. 
And I notice that if the Depth Anything network has more parameters, the range of output disparity will be larger. 
I check the visualizations which has almost no difference (vitl slightly better). 

From my opinion, if the optimization objectives are the same, the outputs should be simillar.
Does anyone have idea on this phenomenon?

The code is:
![image](https://github.com/LiheYoung/Depth-Anything/assets/27566746/a9236de1-792f-46c1-885e-2413971a50da)

vits:
![disp](https://github.com/LiheYoung/Depth-Anything/assets/27566746/a53b6949-3711-4914-bdc8-8f1ccff798e1)

vitb:
![disp](https://github.com/LiheYoung/Depth-Anything/assets/27566746/08a27855-01e2-40d0-9c72-badc983797f0)

vitl:
![disp](https://github.com/LiheYoung/Depth-Anything/assets/27566746/0b1fa6ca-5106-4a86-884f-beb77a1493b3)

**Comment by heyoeyo** [comment]
The math can be a bit confusing, but section **3.1. Learning Labeled Images** of the [depth-anything paper](https://arxiv.org/abs/2401.10891) explains that the models are trained to minimize the 'affine-invariant loss'. Which just means that the depth predictions & ground truth are normalized before calculating the error between them. So the end result is that the models 'don't care' about the absolute value of their outputs (e.g. outputting 0-to-20 for vits vs. 0-220 for vitl), just that the relative ordering of values is correct compared to the ground truth.

As for why the different model sizes output results in consistently different ranges, I would guess it's a side-effect of the DINOv2 image encoder (used in depth-anything models) which has a known pattern of having increasingly 'high norm' tokens in later layers. The reason I say this is that the max-values you've reported seem to closely correlate with the norms of the final output layer of the models (at least from my own [experiments](https://github.com/heyoeyo/muggled_dpt/tree/main/experiments#block-norm-visualization)). There's more info about this in the paper "[Vision Transformers Need Registers](https://arxiv.org/abs/2309.16588)" if case you're interested.

**Comment by WeijianZhang123** [comment]
> The math can be a bit confusing, but section **3.1. Learning Labeled Images** of the [depth-anything paper](https://arxiv.org/abs/2401.10891) explains that the models are trained to minimize the 'affine-invariant loss'. Which just means that the depth predictions & ground truth are normalized before calculating the error between them. So the end result is that the models 'don't care' about the absolute value of their outputs (e.g. outputting 0-to-20 for vits vs. 0-220 for vitl), just that the relative ordering of values is correct compared to the ground truth.
> 
> As for why the different model sizes output results in consistently different ranges, I would guess it's a side-effect of the DINOv2 image encoder (used in depth-anything models) which has a known pattern of having increasingly 'high norm' tokens in later layers. The reason I say this is that the max-values you've reported seem to closely correlate with the norms of the final output layer of the models (at least from my own [experiments](https://github.com/heyoeyo/muggled_dpt/tree/main/experiments#block-norm-visualization)). There's more info about this in the paper "[Vision Transformers Need Registers](https://arxiv.org/abs/2309.16588)" if case you're interested.

Thanks! It helps a lot!
