### ISSUE TITLE
TypeError:__init__() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by kangcaidao** [LiheYoung/Depth-Anything#166]

**Comment by yourmoln** [comment]
You can see #105. It might solve your troubles.

**Comment by JesseZZZZZ** [comment]
For me, it is a problem with internet connection. I used` HF_ENDPOINT=https://hf-mirror.com` and fixed the problem (of course, only if you are in mainland China)

**Comment by Choujim** [comment]
> For me, it is a problem with internet connection. I used` HF_ENDPOINT=https://hf-mirror.com` and fixed the problem (of course, only if you are in mainland China)

Thanks!, An elegeant solution to Chinese special version, just replace the default constant: `_HF_DEFAULT_ENDPOINT`

**Comment by LiheYoung** [comment]
It seems this issue has been resolved. Thank you for your answers! I will close it for now.
