### ISSUE TITLE
Utilization in VO and SLAM

### ISSUE THREAD

**Issue by JesseZZZZZ** [LiheYoung/Depth-Anything#167]
Hi! Thank you for your great work! I want to use it in my Visual Odometry task, as a tool to gain depth map from RGB input. So, I wonder whether Depth Anything can get the absolute depth, or does the relevant value of depth keeps the same for video input? For instance, if the camera circles a table, can the depth of the table in the depth map keeps stable?

Looking forward to your reply, and Thank you!

**Comment by LiheYoung** [comment]
Hi, you can use our [metric depth models](https://github.com/LiheYoung/Depth-Anything/tree/main/metric_depth). If your camera intrinsics are very different from our training one, there may exist a scaling factor between the predicted depth and the groundtruth depth. But according to our experiments, the scale is relatively consistent across video frames and image regions.

**Comment by JesseZZZZZ** [comment]
> Hi, you can use our [metric depth models](https://github.com/LiheYoung/Depth-Anything/tree/main/metric_depth). If your camera intrinsics are very different from our training one, there may exist a scaling factor between the predicted depth and the groundtruth depth. But according to our experiments, the scale is relatively consistent across video frames and image regions.

Thank you!
