### ISSUE TITLE
Android Deployment Recommendation

### ISSUE THREAD

**Issue by DakeQQ** [LiheYoung/Depth-Anything#169]
您好，推荐一个基于ONNX Runtime的安卓布署项目，Depth Anything-Small (resized) 在2*A76核心上，能跑出11FPS的成绩，8Gen2能达到22FPS.

Hello, We recommend an Android deployment project based on ONNX Runtime. The Depth Anything-Small model (resized) achieves 11FPS on dual A76 cores and hits 22FPS on 8_Gen2.

https://github.com/DakeQQ/YOLO-Depth-Estimation-for-Android

**Comment by LiheYoung** [comment]
Thank you! We will add this awesome repo in our next update!
