### ISSUE TITLE
Adding support for the Depth Anything model in X-AnyLabeling

### ISSUE THREAD

**Issue by CVHub520** [LiheYoung/Depth-Anything#17]
Hi, @LiheYoung, thank you so much for your outstanding work!

I've successfully integrated Depth Anything into [X-AnyLabeling](https://github.com/CVHub520/X-AnyLabeling), bringing a significant advancement to our efforts. Depth Anything proves to be a highly practical solution for robust monocular depth estimation, trained on a combination of 1.5 million labeled images and over 62 million unlabeled images. This integration enhances X-AnyLabeling, providing a more comprehensive and industrial-grade solution for image data engineering.

It's important to note that this isn't an issue but rather a celebration of the successful integration. Once again, thanks for your exceptional contribution. Looking forward to more successful collaborations in the future!

**Comment by LiheYoung** [comment]
Hi @CVHub520, thank you a lot for your efforts! I will update my README to link to your amazing repository.

**Comment by LiheYoung** [comment]
Added! Thank you again!
