### ISSUE TITLE
after fine-tune on my own dataset and try to test, got unexpected error

### ISSUE THREAD

**Issue by visonpon** [LiheYoung/Depth-Anything#180]
Hi, @LiheYoung ,thank you for sharing this wonderful work, when test on my fine-tuned model, I got missing keys error like below :
`"conv2.weight','conv2.bias','seed_bin_regerssor._net.0.weight'....`

I just load my own data and use the command to fine-tune:
`python train_mono.py -m zoedepth -d my_data --pretrained_resource="./depth_anything_vitl14.pth"` ,
 and at test phase, i use:
` python run.py --encoder=vitl / load_from='my fine_tune model' / --localhub.`

Since this missing keys are from zoedepth,  it seems train phase use zoedepth model but test use depth_anything, so I write a test file and get the model use `build_model `based on train_mono.py and load my fine-tune model instead of using DPT_DINOv2 in run.py, everything is normal except the test results are not good.

Hope you can give some advice ,thanks~

**Comment by swing2331** [comment]
@visionpon ，Hello, may I ask how you achieved fine-tuning on your own dataset? Can you provide some detailed guidance?

I am also trying to make slight adjustments on the custom dataset, but I have no idea how to modify the configuration file...

**Comment by visonpon** [comment]
it's easy to  write your own data load file based on the scripts in `metric_depth/zoedpth/data/` @swing2331

**Comment by jianingwangind** [comment]
@visonpon hi i am new to depth estimation. Do you need gt depths for fine tuning or you only use the unlabeled raw img data? Thanks
