### ISSUE TITLE
Inquiry about fisheye or 360 degree camera

### ISSUE THREAD

**Issue by BeginerYJH** [LiheYoung/Depth-Anything#181]
I use this model to estimate real depth with 360 Omnicam.

When I apply this in panorama Image with distortion correction, edge object(e.g. cars, people) depth estimation average errors are almost 2~30%.

So, I want to clarify whether the large field of view affect precision of result.

Thank you for advance.
Best regards.

**Comment by XinnWang** [comment]
@BeginerYJH Hi, how did you solve this problme? may i ask your solution?
