### ISSUE TITLE
how load model form local host?

### ISSUE THREAD

**Issue by machine52vision** [LiheYoung/Depth-Anything#19]
how load model form local host?

**Comment by LiheYoung** [comment]
We have added a solution in the README: https://github.com/LiheYoung/Depth-Anything#no-network-connection-cannot-load-these-models

**Comment by xxxxzsxxxx** [comment]
> 我们在自述文件中添加了一个解决方案：https://github.com/LiheYoung/Depth-Anything#no-network-connection-cannot-load-these-models

本地加载模型时提示缺少from_pretrained()函数参数，一个config文件？

**Comment by LiheYoung** [comment]
@xxxxzsxxxx  You should also download the config file in the huggingface repo.

**Comment by jx-99321** [comment]
@LiheYoung I have stored the config and checkpoint files under the folder checkpoints/depth_anything_vitx14，Where should I put the checkpoints folder? DepthAnything？
![Uploading clipbord_1706248272473.png…]()

**Comment by LiheYoung** [comment]
You can simply put the ``checkpoints`` folder under the current path, *e.g.*, the ``Depth-Anything`` root path. Then you can load our models via:
```python
depth_anything = DepthAnything.from_pretrained('./checkpoints/depth_anything_vitl14', local_files_only=True)
```
