### ISSUE TITLE
Sparse Prior

### ISSUE THREAD

**Issue by h1063135843** [LiheYoung/Depth-Anything#190]
To get a metric depth esitmation result, fine tune with supervised depth is needed. 
It is not friendly to custom dataset, and accompanied with some problems discussed in [issue 36](https://github.com/LiheYoung/Depth-Anything/issues/36)
Is there anyway to combine relative depth estimation result and sparse prior such as sfm or lidar ? 
Add a post processing step, using projected sparse depth map to correct relative depth estimation.

**Comment by 1ssb** [comment]
Short answer: not really!

Adding a post processing step unless you learn a warping function which can somehow magically turn your relative scales wrt the sparse prior which is noisy for sure into a metric representation, not really.

**Comment by h1063135843** [comment]
> Short answer: not really!
> 
> Adding a post processing step unless you learn a warping function which can somehow magically turn your relative scales wrt the sparse prior which is noisy for sure into a metric representation, not really.

In fact, after a day's survey, I have found some work foucs on learning such a warping fuction.
Using sparse prior to get a depth map, is named as depth completion task. Many of them require training with image, supervised depth and sparse prior together. 
Paper [1] cuts a depth estimation model into two parts: front and rear, and propose a plug and play module warping the output of the front part. After warpping and the rear part of model,  the estimated depth is more close to the sparse prior.  This method doesn't need retraining.
Paper [2] takes rgb, sparse depth, initial depth (like depth anyting output) as input together. It iteratively propogate sparse depth and finally get a refined depth map.  Section 2.3 has a good summary about this field, sparse depth refinement.
Maybe combine depth anything result and [1], it can arrive comparable peformance without metric retraining on kitty dataset.
Do you think it is possible? And any suggestion?

[[1] Plug-and-Play: Improve Depth Prediction via Sparse Data Propagation](https://github.com/zswang666/PnP-Depth)
[[2] Masked Spatial Propagation Network for Sparsity-Adaptive Depth Refinement](https://github.com/jyjunmcl/MSPN_SDR)

**Comment by 1ssb** [comment]
Apologies for the delayed reply, this seems less of an issue and more of a discussion, we can continue this somewhere else because its not related to the implementation.

**Comment by Jayzhang2333** [comment]
Check this out https://github.com/isl-org/VI-Depth/tree/main
