### ISSUE TITLE
BDD100K: 8M Images?

### ISSUE THREAD

**Issue by ShenZheng2000** [LiheYoung/Depth-Anything#194]
According to Table 1 (screenshot below), the model was trained on 8 million unlabeled images from BDD100K. However, the downloadable BDD100K dataset contains only 100,000 images. 

Therefore, I wonder if the authors sample these 8 million images from video clips. If so, please provide the list of videos and the sampling rate. Thanks!

![image](https://github.com/LiheYoung/Depth-Anything/assets/69662345/840eef30-bbbe-462d-b1f6-6e2e32fb4f14)

**Comment by LiheYoung** [comment]
Yes, we **evenly** sample 8M images from the raw videos.

**Comment by ShenZheng2000** [comment]
Could you please specify the **sampling rate** (extract 1 frame from how many frames)?

**Comment by LiheYoung** [comment]
Our sampling rate is one image / 10 frames. We sample them from 70K training videos of BDD100K.

**Comment by ShenZheng2000** [comment]
Thanks.
