### ISSUE TITLE
Batch Inference

### ISSUE THREAD

**Issue by maurovitaleBH** [LiheYoung/Depth-Anything#199]
Hello, first of all, congrats for your amazing work.

Since image preprocessing keeps aspect ration, loaded images after preprocessing have different shapes. 
What do you suggest to perform batch inference? Padding? There is some reference inside the repo on how to do batch inference?

Thanks

**Comment by LiheYoung** [comment]
Yes, this practice will resize all images to 518x518. I think it will produce satisfying results in most cases, as long as the original aspect ratio is not too large.

**Comment by maurovitaleBH** [comment]
Thank you a lot 🙏🏼

**Comment by markany-yhkwon** [comment]
<img width="872" alt="스크린샷 2024-06-22 오후 9 05 52" src="https://github.com/LiheYoung/Depth-Anything/assets/101165778/11b0d285-f729-463b-bea1-89a9071b90b1">


@maurovitaleBH I tested depth anything v2 with padded images. I think we should take care of padding.

**Comment by maurovitaleBH** [comment]
I also tested padding and something it seems that is not working properly. In particular, black borders are detected as very close
