### ISSUE TITLE
How to recover point cloud from depth map?

### ISSUE THREAD

**Issue by runnerhdh** [LiheYoung/Depth-Anything#20]
hi, thanks for your great work. 
I run the `run.py` on my custom images, and I'm having difficulty when using intrinsics and inferred depth map to recover point cloud. The pixel value of the 16-bit unit depth map does not seem to be relative depth, because I found that the pixel value in the far distance is smaller. Please tell me the correct meaning of the pixel value of the 16-bit depth map (inferred in run.py#L72 just as follows).
https://github.com/LiheYoung/Depth-Anything/blob/c3390b83bbab28127113fec9a974bccdc139bccb/run.py#L72-L73

**Comment by 1ssb** [comment]
Same question here. NO transformation, still seems to be a bit more effective, is it already in the 3d space?

**Comment by LiheYoung** [comment]
Thank you for discussions. Besides, @1ssb provided an amazing depth to point cloud script here:
https://github.com/LiheYoung/Depth-Anything/blob/main/metric_depth/depth_to_pointcloud.py

**Comment by 1ssb** [comment]
@LiheYoung I recommend closing this issue and closing all the related
issues (there are quite a few) by redirecting them to this one, if you are
satisfied with the discussion. I think I have answered possible doubts
quite extensively.

There could be, however, new issues to this script and its related utility
for which I recommend tagging me in the newer issues.

Thanks and congratualtions on your amazing work!
