### ISSUE TITLE
comfyui extension

### ISSUE THREAD

**Issue by LyazS** [LiheYoung/Depth-Anything#22]
anyone would like to make an extension for comfyui？❤

**Comment by mskiller** [comment]
Well you can already use it using controllnet.

**Comment by LiheYoung** [comment]
Hi @LyazS, you may refer to this project: https://github.com/Fannovel16/comfyui_controlnet_aux?tab=readme-ov-file#depth-anything--zoe-depth-anything

**Comment by LyazS** [comment]
> Hi @LyazS, you may refer to this project: https://github.com/Fannovel16/comfyui_controlnet_aux?tab=readme-ov-file#depth-anything--zoe-depth-anything

so great work, thx😝
