### ISSUE TITLE
DepthAnything example for the web and without any servers... 

### ISSUE THREAD

**Issue by akbartus** [LiheYoung/Depth-Anything#228]
Hi! 

I just wanted to take a moment to thank you for the fantastic repository and model. I’ve been experimenting with DepthAnything and have developed a browser-based implementation of it, powered by ONNX.

You can check it out here:

Github Repo: https://github.com/akbartus/DepthAnything-on-Browser 
Interactive Demo: https://depthanything.glitch.me/

Feel free to share it on your page if you think it might be of interest!

**Comment by LiheYoung** [comment]
Hi @akbartus, thank you very much for your contribution! I will add this to our README in the next update.

**Comment by akbartus** [comment]
Thank you. Feel free to close the issue.

**Comment by NikolasE** [comment]
That's a nice tool! Which metric model are you running? It would also be nice to be able to pass the focal length as a parameter instead of using a fixed fov of 45.

**Comment by akbartus** [comment]
> That's a nice tool! Which metric model are you running? It would also be nice to be able to pass the focal length as a parameter instead of using a fixed fov of 45.

@NikolasE thanks for the feedback. In the example it is small quantized model. Will update example to include interactive sliders for FOV and others.

**Comment by akbartus** [comment]
@NikolasE created example with sliders, you can check it here: https://depthanything.glitch.me/webgpu-sliders.html but for DepthAnything v2 already. Updated repo accordingly.
