### ISSUE TITLE
Deploy the model on OpenXLab

### ISSUE THREAD

**Issue by yinfan98** [LiheYoung/Depth-Anything#23]
Hi, I really love the work, can I deploy this work on openxlab？

**Comment by LiheYoung** [comment]
Hi, please feel free to do so.

**Comment by yinfan98** [comment]
Hi, I finish that~
this is a [demo](https://openxlab.org.cn/apps/detail/yyfan/depth_anything), and I also upload the [depth anything vitl](https://openxlab.org.cn/models/detail/yyfan/depth_anything_vitl14), [depth anything vitb](https://openxlab.org.cn/models/detail/yyfan/depth_anything_vitb14), [depth anything vits](https://openxlab.org.cn/models/detail/yyfan/depth_anything_vits14) models on OpenXLab. 
Is it possible to include these links in the README as well? This is a good option for those who have difficulty accessing HuggingFace...

**Comment by LiheYoung** [comment]
Thank you a lot! I will add this to our README!

**Comment by LiheYoung** [comment]
Added. Thank you!
