### ISSUE TITLE
About Table 6 in the Original Paper

### ISSUE THREAD

**Issue by zhangzw12319** [LiheYoung/Depth-Anything#25]
Thanks for your excellent and outstanding efforts in this work! Really love the work. 

As for `the transferring performance` experiments in Table 6, I have some questions about the detailed training settings:
- Is either `ViTS`, `ViTB` or `ViTL` used for this experiment?
- Is this model trained from scratch (using DinoV2 original weights and finetuning on speific single dataset) in Table 6, or trained by self-supervised manner on the whole labeled 1.5M and 65M unlabeled dataset? In other words, is there self-supervision manner involved in this experiment settings?

THX a lot for your kind reply and description.

**Comment by LiheYoung** [comment]
Thank you for your questions.

1. ViT-L is used.
2. The model is fine-tuned from DINOv2 weights, without further performing SSL on our 1.5M + 62M depth data.

**Comment by zhangzw12319** [comment]
Thx for your kind information !
