### ISSUE TITLE
Unstable results

### ISSUE THREAD

**Issue by Qk527** [LiheYoung/Depth-Anything#26]
Hi! Great work!!! very usefull.
One question: is it possible that I have different results in the same image on several occasions? maybe because the interpolation or resize method in transform?

**Comment by LiheYoung** [comment]
Thank you for your question. I made a simple attempt and found that there are very subtle differences on several runs. However, the fluctuation is negligible, *e.g.*, the difference value is around 0 ~ 1e-5 within multiple runs, whereas the depth output is larger than 1e2.
