### ISSUE TITLE
Point cloud from depth map?

### ISSUE THREAD

**Issue by antithing** [LiheYoung/Depth-Anything#31]
Hi, and thanks for making this code available!

Is it possible to calculate a 3d point cloud from the depth map? 

Are the depth maps at consistent, or arbitrary scale?

Thanks again

**Comment by 1ssb** [comment]
Arbitrary scale as far as I found.

**Comment by loevlie** [comment]
I would update the focal_length here https://github.com/LiheYoung/Depth-Anything/blob/5935968f82018d68fff44946573d34cdf27db827/metric_depth/evaluate.py#L78

Then use this to get the 3D point cloud: https://github.com/LiheYoung/Depth-Anything/blob/5935968f82018d68fff44946573d34cdf27db827/metric_depth/zoedepth/utils/geometry.py.

**Comment by LiheYoung** [comment]
Please refer to this discussion: https://github.com/LiheYoung/Depth-Anything/issues/36
