### ISSUE TITLE
Any visualization as 3d point cloud to see how good it visualized in 3d space?

### ISSUE THREAD

**Issue by lucasjinreal** [LiheYoung/Depth-Anything#39]
Any visualization as 3d point cloud to see how good it visualized in 3d space?

**Comment by LiheYoung** [comment]
Maybe this project can help you a little: https://huggingface.co/spaces/Xenova/depth-anything-web

**Comment by ymzhang0303** [comment]
> You may find this file and issue helpful:
> 
> * https://github.com/LiheYoung/Depth-Anything/blob/main/metric_depth/depth_to_pointcloud.py
> * issue [true metric depth values #36](https://github.com/LiheYoung/Depth-Anything/issues/36)
> 
> Maybe this project can also help you a little: https://huggingface.co/spaces/Xenova/depth-anything-web.

@LiheYoung Thanks for your reply and help! I am working on 1080p image, and I find that https://github.com/LiheYoung/Depth-Anything/blob/main/metric_depth/depth_to_pointcloud.py generates poor 3D points, while https://huggingface.co/spaces/Xenova/depth-anything-web is pretty good. May I know how depth-anything-web generate 3D points from depth map? Thanks!

**Comment by I3aer** [comment]
Nobody answerered

> > You may find this file and issue helpful:
> > 
> > * https://github.com/LiheYoung/Depth-Anything/blob/main/metric_depth/depth_to_pointcloud.py
> > * issue [true metric depth values #36](https://github.com/LiheYoung/Depth-Anything/issues/36)
> > 
> > Maybe this project can also help you a little: https://huggingface.co/spaces/Xenova/depth-anything-web.
> 
> @LiheYoung Thanks for your reply and help! I am working on 1080p image, and I find that https://github.com/LiheYoung/Depth-Anything/blob/main/metric_depth/depth_to_pointcloud.py generates poor 3D points, while https://huggingface.co/spaces/Xenova/depth-anything-web is pretty good. May I know how depth-anything-web generate 3D points from depth map? Thanks!

Nobody knows how the huggingface code generates better point cloud representation? It is really interesting :/
