### ISSUE TITLE
Evaluation of relative depth

### ISSUE THREAD

**Issue by kishore-greddy** [LiheYoung/Depth-Anything#43]
Hello, 

Thanks for your amazing work. 

I have a question regarding evaluating relative depth. I see from your paper that the errors are as below:
![image](https://github.com/LiheYoung/Depth-Anything/assets/76811772/c317fb1a-7954-4468-8cec-9fceb2e71b47)
How to reproduce these errors from the pretrained weights that are available? Specifically, is there an eval.py for relative depth evaluation? Or how did you get these numbers?

What I tried doing is :
1. Convert disparity to depth (by taking the inverse)
2. Find the median of GT and median of predicted depth and use the ratio to scale the prediction
3. Compute the errors.

By doing this my errors are in the range of 30-40% which is nowhere close to the near 7-8% that you report. 
It would be really helpful if you let me know how you computed these numbers. Thanks in advance 👍

**Comment by Davidyao99** [comment]
@kishore-greddy  Hi, I am also trying to evaluate DepthAnything. Did you manage to reproduce the results? How did you go about implementing the evaluation? Thank you!
