### ISSUE TITLE
Better resolution of depthmap?

### ISSUE THREAD

**Issue by luuude** [LiheYoung/Depth-Anything#45]
Hi this work is great! I have modified it a bit to read and write EXR files in float and also add the depth in the proper Z-buffer channel with OpenImageIO. I have been experimenting with trying to get better resolution by changing the resize values and it works to a degree when I run 777 pixels but after that up to when i fill up my vram at 24GB at 2072 it looks much worse.

transform = Compose([
        Resize(
            width=2072,
            height=2072,
![Screenshot from 2024-01-26 21-30-59](https://github.com/LiheYoung/Depth-Anything/assets/13946001/9d326e21-dd35-4441-8e6f-b3ebba6f88d8)

777 on the left and 2072 to the right

Can I do anything else to get the same nice definition but with crisper edges? Do I need to retrain?

**Comment by LiheYoung** [comment]
Yes, since our models are trained by resizing images to 518 resolution, if you want to use a much larger resolution, you may need to re-train the model with your own data.

**Comment by luuude** [comment]
Ahh yes I thought so, I probably dont have the resources to train it myself anyway. From the other issues here it seems you will not release the full code used for training? 
 will try to marry your code with NVDS to get it even more temporally stable.

And again really awesome work! Congratulations!

**Comment by LiheYoung** [comment]
Yes, we currently do not have the plan to release the full training code. We may provide models supporting large resolutions in the future, please stay tuned. Thank you!

**Comment by luuude** [comment]
Yes I saw you mention that in the paper, up to 1000 pixels. Sounds great if it happens, how Munch time and hardware world you need? And is it not possible to transfer some learning from this model?

**Comment by Gear-dev-sudo** [comment]
> Hi this work is great! I have modified it a bit to read and write EXR files in float and also add the depth in the proper Z-buffer channel with OpenImageIO. I have been experimenting with trying to get better resolution by changing the resize values and it works to a degree when I run 777 pixels but after that up to when i fill up my vram at 24GB at 2072 it looks much worse.
> 
> transform = Compose([ Resize( width=2072, height=2072, ![Screenshot from 2024-01-26 21-30-59](https://private-user-images.githubusercontent.com/13946001/300106442-9d326e21-dd35-4441-8e6f-b3ebba6f88d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDk0NjAsIm5iZiI6MTcwOTY0OTE2MCwicGF0aCI6Ii8xMzk0NjAwMS8zMDAxMDY0NDItOWQzMjZlMjEtZGQzNS00NDQxLThlNmYtYjNlYmJhNmY4OGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE0MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1Y2UzNWFjZTU1N2Q4MzM0ZjhhZTNhYTcyNmQ1ZjVmMTYzZTRlNjhmNDJmMTIxYzRhNDczYzA3M2VlY2FjMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Qe2AGjOAoNKObrsuUciOXT95Za5ElBE_MTe-apgX7U)
> 
> 777 on the left and 2072 to the right
> 
> Can I do anything else to get the same nice definition but with crisper edges? Do I need to retrain?

Hi luude, can you elaborate on how to read and write exr files in this model? Been trying to do it but having troubles since I'm practical an amateur in CV.

**Comment by Gear-dev-sudo** [comment]
Thank you for that!
