### ISSUE TITLE
Could you release a tiny/nano version of depth anything pth file?

### ISSUE THREAD

**Issue by zhongqiu1245** [LiheYoung/Depth-Anything#48]
Hello!
Thank you for your amazing job!
I have converted depthanything_vits14 into onnxruntime(cpu) version (to make it deploy on lite-device, for example, Raspberry Pi/CPU of laptop, easily)
For now, I test `depthanything_vits14.onnx` on x64 cpu of my laptop, and fps=3.5 (for 518*518, pytorch)
I quant this onnx, the fps=3.7fps (for 518*518, quant-static-onnxruntime)
I want to fps>=24fps, but `depthanything_vits14` doesn't achieve that. And I think it size of params is too heavy for lite-CPU?
I do like your job, I want to deploy it on CPU so that make this wonderful thing more powerful.
Could you release a tiny/nano version of depth anything pth file to make it faster on CPU?
Thank you in advance!

**Comment by LiheYoung** [comment]
Thank you for your attention. Currently, we have not developed even smaller models than our released Depth-Anything-small. But we will keep your request in mind, and hopefully, we can release a much lighter model in future updates.

**Comment by jamesbaker1** [comment]
Thank you for all your work! Any update on this? Would love to see it!

**Comment by trpnhii** [comment]
@zhongqiu1245 
Hello!
I’m impressed with your work on converting depthanything_vits14 to an onnxruntime version for CPU deployment. I’m currently working on a similar project aiming to run the model on a CPU, and my target is to achieve just 5 FPS.
I was wondering if you could share the source code and the ONNX file with me. It would be incredibly helpful for my project.
Thank you in advance!

**Comment by jamesbaker1** [comment]
Hi @nhiichan 

Want to collaborate? I am trying to get it to run fast on Raspberry PI CPU or Vulkan RPI GPU? Shoot me an email at james.baker1628@gmail.com
