### ISSUE TITLE
models marked unsafe by HuggingFace

### ISSUE THREAD

**Issue by slashdottir** [LiheYoung/Depth-Anything#50]
<img width="746" alt="image" src="https://github.com/LiheYoung/Depth-Anything/assets/47145634/5a702bba-988e-4ec1-a3c4-7402e3feb9d6">

https://huggingface.co/spaces/LiheYoung/Depth-Anything/tree/main/checkpoints_semseg

**Comment by LiheYoung** [comment]
Thank you for your reminder. We will update these two checkpoints.
