### ISSUE TITLE
Depth_Anything inside PRISMA

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [LiheYoung/Depth-Anything#52]
I added this model to [PRISMA](https://github.com/patriciogonzalezvivo/prisma). A multi-infer project that let you make depth inferences along MiDAS v3.1, ZoeDepth, PatchFusion and Marigold; and segmentation of dynamic objects on a scene.

https://github.com/patriciogonzalezvivo/prisma

Depth is encoded in such a way that's easy to be load in Blender or any other rendering engine for visualization

For videos is also possible to do RAFT and COLMAP.

**Comment by LiheYoung** [comment]
Thanks! I will update our document.
