### ISSUE TITLE
Segmentation is not working

### ISSUE THREAD

**Issue by MrNeRF** [LiheYoung/Depth-Anything#53]
Thank you for this wonderful work. 
I tried to run segmentation as described here: https://github.com/LiheYoung/Depth-Anything/tree/main/semseg

But I could not get it properly working. It has some obvious bugs: In dinov2.py it should be something like
self.dinov2 = torch.hub.load('facebookresearch/dinov2', 'dinov2_vitl14')
and not as here provided: https://github.com/LiheYoung/Depth-Anything/blob/main/semseg/dinov2.py#L18

Here is another crash I had to fix after following the step you are describing:
https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/models/segmentors/encoder_decoder.py#L284

Finally, I could make it not crash but the output is very wrong. Any idea what the issue might be as you also report sota on segmentation?

![result_demo](https://github.com/LiheYoung/Depth-Anything/assets/33876434/148d65d1-f7fa-4961-a3d2-7d85814d84d5)

**Comment by LiheYoung** [comment]
Hi, sorry for the confusion. We provide the ``torchhub`` directory [here](https://github.com/LiheYoung/Depth-Anything/tree/main/torchhub). Please put it under your working space.

**Comment by MrNeRF** [comment]
Thank you for you help. 

Unfortunately, it does not run with mmsegmentation. I get all the examples running that come with mmsegmentation. So this is not the issue. But when I try depth anything segmentations, it is not working. It starts to crash again.

This line is also wrong:            
> self.dinov2 = torch.hub.load('torchhub/facebookresearch_dinov2_main', 'dinov2_vit14', source='local', pretrained=False)

There is no dinov2_vit14. It must be dinov2_vitl14 I think. However, it does not integrate properly with mmsegmentation.
Did you use any specific version of mmsegmentation? Is the Readme some essential information missing? I am a bit puzzled why this is not working.

**Comment by MrNeRF** [comment]
Thank you for your answer!
I guess mmsegmentation can be in its own conda environment? It does not need to be a subfolder of depth anything I assume.

So basically installing an isolated mmsegmentation project and then following the 4 steps?

I will retry it again later tonight. I really appreciate your help. Thank you!

**Comment by LiheYoung** [comment]
Yes, there is no need to install mmseg as a subfolder of Depth Anything. Just necessary files mentioned in the four steps into your mmseg project. We have updated the files under [``semseg``](https://github.com/LiheYoung/Depth-Anything/tree/main/semseg). Please use the latest files. Thank you.

**Comment by MrNeRF** [comment]
So this is what I get:
> Traceback (most recent call last):
  File "tools/test.py", line 123, in <module>
    main()
  File "tools/test.py", line 116, in main
    runner = Runner.from_cfg(cfg)
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 462, in from_cfg
    runner = cls(
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 429, in __init__
    self.model = self.build_model(model)
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 836, in build_model
    model = MODELS.build(model)
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/paja/projects/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 92, in __init__
    self._init_decode_head(decode_head)
  File "/home/paja/projects/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 102, in _init_decode_head
    self.decode_head = MODELS.build(decode_head)
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/paja/micromamba/envs/openmmlab/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/paja/projects/mmsegmentation/mmseg/models/decode_heads/mask2former_head.py", line 42, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'in_channels'

I am running the following command:
> python3 tools/test.py configs/depth_anything/depth_anything_large_mask2former_16xb1_80k_cityscapes_896x896.py cityscapes_vitl_mIoU_86.4.pth

In this repo (depth anything) I am on HEAD (e911178017ef4a3039c3599ca20327961388f932)
In the mmsegmentation repo I am on HEAD (c685fe6767c4cadf6b051983ca6208f1b9d1ccb8)

The versions are:
mmcv==2.1.0,  mmengine=0.10.2 (was before on 0.10.3 but has same error)
Obviously mask2former_head.py get some variables it does not like. So that's why I think there is some incompatibility and I am scratching my head how to get this running (without diving fully into the code base to understand all details)

Thank a lot for your help!

**Comment by LiheYoung** [comment]
Please try:
```bash
pip install "mmdet>=3.0.0rc4"
```
And then re-run the test command.

**Comment by MrNeRF** [comment]
Thank you. That did the trick! It runs. Maybe some additional info might be helpful for others to get this running as well.

**Comment by LiheYoung** [comment]
Thank you for your feedback! I will update the semseg README.

**Comment by MACILLAS** [comment]
@LiheYoung  thank you very much for your response to this issue it was very helpful!

I just wanted to add that there seems to be some issue with mmsegmentation using Pytorch 2, running the test script. I tried both 2.1 and 2.2 and ended up installing Pytorch 1.13 with Cuda 11.7, which worked for me.

Hope this helps someone... :)

**Comment by cht619** [comment]
在训练seg的时候，有用到提到的一些loss吗
