### ISSUE TITLE
setup.py?

### ISSUE THREAD

**Issue by affromero** [LiheYoung/Depth-Anything#6]
Hello, nice stuff.
Can you add a setup.py or pyproject.toml? So it can be used as a package (pip install/poetry add) without cloning the repo?

**Comment by LiheYoung** [comment]
Hi, we have updated the ways to using our Depth Anything models. You can easily use them within 3 lines of code via the ``transformers`` library without cloning this repo. See [here](https://github.com/LiheYoung/Depth-Anything?tab=readme-ov-file#do-not-want-to-define-image-pre-processing-or-download-model-definition-files) for details.
