### ISSUE TITLE
Runtime error on Windows

### ISSUE THREAD

**Issue by BattleAxeVR** [LiheYoung/Depth-Anything#65]
Hi there, I am very excited to test and modify this project, however I don't have a dedicated Linux machine currently and would like to run this on Windows with my RTX 4090 GPU via Cuda / pytorch.

There is a missing dependency for Windows to run this sample, because there isn't currently a windows build to one of the python modules, I can't remember which offhand.

**Comment by LiheYoung** [comment]
According to the feedback from others: https://github.com/LiheYoung/Depth-Anything/issues/44, it seems our model can also be used in Windows.
