### ISSUE TITLE
code of Transformer.js project

### ISSUE THREAD

**Issue by SunzeY** [LiheYoung/Depth-Anything#73]
[https://huggingface.co/spaces/Xenova/depth-anything-web](https://huggingface.co/spaces/Xenova/depth-anything-web) is a wonderful project! Is it possible to make its code available to us?

**Comment by LiheYoung** [comment]
Hi, I am not the author of this project, but you may find the open-sourced code here:
https://github.com/xenova/transformers.js/tree/main/examples/depth-anything-client

**Comment by SunzeY** [comment]
Thanks for sharing!
