### ISSUE TITLE
ONNX export

### ISSUE THREAD

**Issue by fabio-sim** [LiheYoung/Depth-Anything#8]
Hi, authors. Congratulations on the amazing work!

I've exported Depth Anything to ONNX at https://github.com/fabio-sim/Depth-Anything-ONNX. It would be great if you could link it here too :)

**Comment by LiheYoung** [comment]
Hi, thank you for your efforts! I will shortly add this link to our README.

**Comment by LiheYoung** [comment]
Added! Thank you again!
