### ISSUE TITLE
Tolerance margin for feature alignment

### ISSUE THREAD

**Issue by TomTomTommi** [LiheYoung/Depth-Anything#80]
Hi, very interesting work!

I am a little bit confused with the tolerance margin for feature alignment. As the paper says "If the cosine similarity of f and f′ has surpassed α, this pixel will '**not**' be considered in our L_feat." 

I am wondering if this means that only the `cos(f, f') < α` part is computed for this loss.

**Comment by tcourat** [comment]
Probably the loss can be rewritten as loss=max(0, cos(f, f')-α). Hence is the cosine similarity is below alpha, then the loss will be zero (and thus not used for backward propagation).

**Comment by LiheYoung** [comment]
Hi, thank you for your question.

There is an incorrect presentation in our arXiv v1 paper. 

The correct presentation should be "If $1 - \cos(f_i, f_i')$ is already smaller than $\alpha$, the pixel $i$ will not be considered in our $\mathcal{L}_{feat}$"". We set $\alpha$ as 0.15. 

It means that if the two features are very similar (similarity > 0.85), we will stop optimizing the feature alignment loss for this pixel.

We will shortly update our manuscript to correct this mistake. Thank you!

**Comment by schatto02** [comment]
Hi, thanks for such great work ! I was wondering which features are used for this loss --- do we use intermediate features or the final encoder features?
