### ISSUE TITLE
ImportError: cannot import name 'DepthAnything' from 'depth_anything.dpt' When using run.py

### ISSUE THREAD

**Issue by FoxTrotte** [LiheYoung/Depth-Anything#89]
Hey everyone !

Trying to use Depth anything for the first time, after I install everything I finally try it out, with the following command
`python run.py --encoder vitl --img-path "F:\Dossiers\Depth Anything\Depth-Anything\Images" --outdir "F:\Dossiers\Depth Anything\Depth-Anything\Images\output" --pred-only --grayscale`

Unfortunately, I just get this:
 `Traceback (most recent call last):
  File "F:\Dossiers\Depth Anything\Depth-Anything\run.py", line 10, in <module>
    from depth_anything.dpt import DepthAnything
ImportError: cannot import name 'DepthAnything' from 'depth_anything.dpt' (F:\Dossiers\Depth Anything\Depth-Anything\depth_anything\dpt.py)`

I am on Windows 10 with an RTX GPU, using python 3.10.6
Do you have any suggestions ? I'd love to use Depth-Anything for video compositing but I'm currently stuck
Thanks!

**Comment by FoxTrotte** [comment]
(Realized I somehow had an old version of dpt.py mixed in with a new run.py)

**Comment by Guansiyu-glitch** [comment]
what‘s your torch version?

**Comment by Guansiyu-glitch** [comment]
i got an error Traceback (most recent call last):
  File "run.py", line 34, in <module>
    depth_anything = DepthAnything.from_pretrained('LiheYoung/depth_anything_{}14'.format(args.encoder)).to(DEVICE).eval()
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/hub_mixin.py", line 558, in from_pretrained
    instance = cls._from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/huggingface_hub/hub_mixin.py", line 778, in _from_pretrained
    model = cls(**model_kwargs)
TypeError: __init__() missing 1 required positional argument: 'config'
how to solve?
