### ISSUE TITLE
Unable to load pre-trained model, unexpected keyword argument 'antagonists'(has been resolved)

### ISSUE THREAD

**Issue by xbxbcvoo** [LiheYoung/Depth-Anything#95]
I followed the instructions and placed the pytorch_model. bin and config.json files in the same specified folder, and made modifications to depth-anything. However, I encountered an error while running run.py:
TypeError: interpolate() got an unexpected keyword argument 'antagonists'
![1](https://github.com/LiheYoung/Depth-Anything/assets/144868407/648f7d1b-8f48-46b6-8586-425c2f101774)

Can anyone guide me on how to solve this problem? Thank you very much

**Comment by heyoeyo** [comment]
It looks like the pytorch interpolate function got updated between versions [1.10](https://pytorch.org/docs/1.10/generated/torch.nn.functional.interpolate.html) and [1.11](https://pytorch.org/docs/1.11/generated/torch.nn.functional.interpolate.html) to include the `antialias` keyword.

So most likely, the error you're getting is from using an older version of pytorch that doesn't support that keyword.

One way to fix the problem would be to update your pytorch installation (i.e. using conda or pip, depending on how it's installed) to a newer version, it needs to be at least v1.11 or higher. That may cause other problems depending gpu support and versions of other libraries (e.g. torchvision), so an alternative solution would be to simply comment out the line that's causing the error. You should find it on [line 204](https://github.com/LiheYoung/Depth-Anything/blob/e7ef4b4b7a0afd8a05ce9564f04c1e5b68268516/torchhub/facebookresearch_dinov2_main/vision_transformer.py#L204) in the file: 
torchhub > facebookresearch_dinov2_main > vision_transformer.py

**Comment by xbxbcvoo** [comment]
> It looks like the pytorch interpolate function got updated between versions [1.10](https://pytorch.org/docs/1.10/generated/torch.nn.functional.interpolate.html) and [1.11](https://pytorch.org/docs/1.11/generated/torch.nn.functional.interpolate.html) to include the `antialias` keyword.
> 
> So most likely, the error you're getting is from using an older version of pytorch that doesn't support that keyword.
> 
> One way to fix the problem would be to update your pytorch installation (i.e. using conda or pip, depending on how it's installed) to a newer version, it needs to be at least v1.11 or higher. That may cause other problems depending gpu support and versions of other libraries (e.g. torchvision), so an alternative solution would be to simply comment out the line that's causing the error. You should find it on [line 204](https://github.com/LiheYoung/Depth-Anything/blob/e7ef4b4b7a0afd8a05ce9564f04c1e5b68268516/torchhub/facebookresearch_dinov2_main/vision_transformer.py#L204) in the file: torchhub > facebookresearch_dinov2_main > vision_transformer.py

In fact, the PyTorch version I am using is 1.9, but it still has this error. But after listening to your suggestion and commenting out the line 204, it works! Thank you very much for your suggestion :)
